### ISSUE TITLE
关于`GUI` 的介绍

### ISSUE THREAD

**Issue by willser** [sunface/BeatAI#11]
### 功能请求
期望对比和介绍大多数`rust`的`gui` `create`，之前在选择`gui`组件时花费了一些时间，如果在这里可以看到相关介绍可以使开发者更快的了解各个`gui`库的特性。

**Comment by BobH-Official** [comment]
据我所知，纯rust的gui可用的并不多。
目前有一个项目 [tuari](tauri.studio) 进入1.0的rc阶段了，是一个electron的替代品（也就是ui部分还是web实现），比electron又小又快，如果需要，可以参考。
web 的ui部分的话可以参考[yew](yew.rs)。
